version: '3'
services:
    semanticelastic_elastic:
        image: elasticsearch:7.17.10
        ports:
            - "9200:9200"
            - "9300:9300"
        volumes:
            - 'semanticelastic:/usr/share/elasticsearch/data'
        networks:
            - semantic
        environment:
            discovery.type: single-node
networks:
    semantic:
        driver: bridge
volumes:
    semanticelastic:
        driver: local
